### ISSUE TITLE
format of input data

### ISSUE THREAD

**Issue by llangnickel** [jwparktom/continual-bert#1]
Hi, 
could you tell me which input format is required for the preprocessing (raw data)? And what is the content of metadata.csv file? 
Would it be possible to upload some example data? 
Thanks in advance!

**Comment by llangnickel** [comment]
Never mind - just found out that metadata.csv comes with CORD-19 data

**Comment by jdubpark** [comment]
Hi, yes, metadata.csv comes from CORD-19 data. If you want the trained checkpoint, I can give it to you so let me know. Cheers.
